### ISSUE TITLE
Account login

### ISSUE THREAD

**Issue by ANuclearError** [obrut-chat/destino#2]
# User Story
As a user
I would like to login to chat
So that I can participate in chat

# Acceptance Criteria
Given the user has an account
When the user logs in
Then the user can participate in chat

# Subtask
- [ ] Create login screen
- [ ] Handle login requests
- [ ] Redirect logged in users to chat
