### ISSUE TITLE
Sending messages

### ISSUE THREAD

**Issue by ANuclearError** [obrut-chat/destino#3]
# User Story
As a user
I would like to send and receive messages
So that I can talk to friends

# Acceptance Criteria
Given the user is logged in
When the user sends a message
Then the message will be sent to all other users

Given the user is logged in
Then messages will be sent to the user

# Subtasks
- [ ] Create chat screen
- [ ] Connect to websocket
- [ ] Create message screen
- [ ] Send messages through websocket
- [ ] Receive messages through websocket
